config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :reviews
  get 'dashboard', to: 'pages#dashboard'
  resources :submissions
  resources :tasks
  get 'course_choice', to: 'tasks#course_choice'
  get 'assignment_choice', to: 'tasks#assignment_choice'
  resources :assignments, except: :index
  resources :courses
  resources :classrooms
  resources :projects, only: :show
  devise_for :users, path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: {
               registrations: 'users/registrations',
               invitations: 'users/invitations'
             }

  root to: "pages#home"
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :submissions
  has_many :projects
  belongs_to :classroom
  belongs_to :assignment

  validates :name, :description, :first_submission_deadline,
            :review_deadline, :second_submission_deadline, presence: true

  validates :review_deadline, comparison: { greater_than: :first_submission_deadline }
  validates :second_submission_deadline, comparison: { greater_than: :review_deadline }

  scope :in_progress, -> { where('second_submission_deadline > ?', DateTime.now) }

  def assign_reviews(reviews_per_project)
    # TODO optimize # of queries?

    shuffled_projects = projects.shuffle
    shuffled_projects += shuffled_projects[0...reviews_per_project]

    shuffled_projects.each.with_index do |project, index|
      reviews_per_project.times do |index_incremented_by|
        break if index + index_incremented_by + 1 >= shuffled_projects.length

        Review.create(project_id: project.id, user_id: shuffled_projects[index + index_incremented_by + 1].student.id)
      end
    end
  end

  def from_assignment_by_teacher?(given_teacher)
    assignment.from_course_by_teacher?(given_teacher)
  end

  def from_classroom_taught_by?(given_teacher)
    classroom.taught_by?(given_teacher)
  end

  def phase
    current_time = DateTime.now

    if current_time < first_submission_deadline
      :first_submission
    elsif current_time < review_deadline
      :review
    elsif current_time < second_submission_deadline
      :second_submission
    else
      :done
    end
  end

  def time_left
    return 'Done' if phase == :done

    self.send("#{phase.to_s}_deadline") - DateTime.now
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  include Pundit::Authorization

  def index
    @tasks = policy_scope(Task)
  end

  def show
  end

  def new
    assignment = authorize policy_scope(Assignment).find(params[:assignment_id])

    @task = Task.new(
      name: assignment.name, description: assignment.description,
      classroom_id: params[:classroom_id], assignment_id: params[:assignment_id]
    )
  end

  def course_choice
    @courses = authorize policy_scope(Course), policy_class: TaskPolicy
  end

  def assignment_choice
    @assignments = authorize policy_scope(Assignment).where(course_id: params[:course_id]), policy_class: TaskPolicy
  end

  def edit
  end

  def create
    @task = authorize Task.new(task_params)

    if @task.save
      redirect_to @task.classroom, notice: "Task was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @task.update(task_params)
      redirect_to task_url(@task), notice: "Task was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy

    redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  private

  def set_task
    @task = authorize policy_scope(Task).find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :classroom_id, :assignment_id, :first_submission_deadline, :review_deadline, :second_submission_deadline)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message

  = f.hidden_field :classroom_id, value: @task.classroom_id
  = f.hidden_field :assignment_id, value: @task.assignment_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :first_submission_deadline
    = f.datetime_field :first_submission_deadline
  .field
    = f.label :review_deadline
    = f.datetime_field :review_deadline
  .field
    = f.label :second_submission_deadline
    = f.datetime_field :second_submission_deadline
  .actions
    = f.submit 'Save'

app/views/tasks/assignment_choice.html.haml
- @assignments.each do |assignment|
  = link_to assignment.name, new_task_path(assignment_id: assignment.id, classroom_id: params[:classroom_id])

app/views/tasks/course_choice.html.haml
- @courses.each do |course|
  = link_to course.name, assignment_choice_path(course_id: course.id, classroom_id: params[:classroom_id])

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Classroom
      %th Assignment
      %th First submission deadline
      %th Review deadline
      %th Second submission deadline
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.classroom.name
        %td= task.assignment.name
        %td= task.first_submission_deadline
        %td= task.review_deadline
        %td= task.second_submission_deadline
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= button_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
.header.flex.justify-between.items-center.mb-10
  .name-and-author
    .text-3xl.font-bold
      = @task.name
  .action-btn
    = link_to new_submission_path(task_id: @task.id, version: :first) do
      .px-12.py-2.rounded-full.bg-gradient-to-br.from-teal-400.to-sky-700.text-white
        Nahrať
.description.mr-80
  = @task.description