config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :reviews
  get 'dashboard', to: 'pages#dashboard'
  resources :submissions
  resources :tasks
  get 'course_choice', to: 'tasks#course_choice'
  get 'assignment_choice', to: 'tasks#assignment_choice'
  resources :assignments, except: :index
  resources :courses
  resources :classrooms
  resources :projects, only: :show
  devise_for :users, path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: {
               registrations: 'users/registrations',
               invitations: 'users/invitations'
             }

  root to: "pages#home"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
    @submission = @review.project.first_submission
    @comments = @review.comments.order(:to_line)
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:state, :project_id, :user_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :state
    = f.number_field :state
  .field
    = f.label :project
    = f.text_field :project
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing reviews

%table
  %thead
    %tr
      %th State
      %th Project
      %th User
      %th
      %th
      %th

  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.state
        %td= review.project
        %td= review.user
        %td= link_to 'Show', review
        %td= link_to 'Edit', edit_review_path(review)
        %td= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Review', new_review_path

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.haml
.test{ data: { controller: 'highlighter' } }
  %pre
    %code{ data: { highlighter_target: 'code' } }
      = @submission.part(to_line: @comments.first&.show_after_line)

  - @comments.each.with_index do |comment, index|
    - next_comment = @comments[index + 1]

    .comment{ data: { from_line: comment.from_line, to_line: comment.to_line, highlighter_target: 'comment' } }
      = comment.content

    %pre
      %code{ data: { highlighter_target: 'code', ln_start_from: comment.show_after_line + 1 } }
        = @submission.part(from_line: comment.show_after_line + 1, to_line: next_comment&.show_after_line)